### ISSUE TITLE
File name casing is incorrect in async-portable

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#101]
![image](https://cloud.githubusercontent.com/assets/374343/12869578/d32c0af8-cd1b-11e5-8012-abd633a0dbf4.png)

Should be lowercase 'b'

**Comment by WestDiscGolf** [comment]
`FitbitAppCredentials` have been done, but not `FitBitHttpClientMessageHandler` ?

**Comment by mxa0079** [comment]
Lol.... My bad.
