### ISSUE TITLE
Remove unneccesary constructors from FitbitClient in V2

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#114]
Remove unnecessary constructors from FitbitClient in V2. Such as: `FitbitClient(HttpClient client` and any other remaining constructor from V1.

This will most likely require updating a few test helper methods.

**Comment by WestDiscGolf** [comment]
#115 :-)

**Comment by mxa0079** [comment]
See comments on #115 However, I think that `FitbitClient(HttpClient client)` does need to be removed. Not core to OAuth1.
