### ISSUE TITLE
Remove all V1 code

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#115]
We should branch the current main into a reference branch (v1-main). Then async portable should become main and remove all code that is not part of V2 (not under portable). We should also then remove Fitbit.Common which fixes #78

**Comment by WestDiscGolf** [comment]
Would fix #73 as well :-)

**Comment by WestDiscGolf** [comment]
Think we can remove the OAuth2 namespace once all v1 and OAuth1 stuff has been removed - no need to differentiate if there is only one :-)
