### ISSUE TITLE
Migrate Log Fat and Log Weight from V1

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#122]
The Log Fat and Log Weight need migrating from V1 - https://github.com/aarondcoleman/Fitbit.NET/commit/f706a134c503029529ff5d2693e66b121a41faa3

This needs to be pre RC

**Comment by mxa0079** [comment]
Given time constrains, moving this to 2.X functionality. New feature will be backward compatible, hence can go into a minor version upgrade.

**Comment by WestDiscGolf** [comment]
@mxa0079 Can we have another milestone/tag thing then for 2.1 and assign this to that then?
