### ISSUE TITLE
Obsolete contructor removal

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#123]
Also remove dependency on AsyncOAuth

**Comment by mxa0079** [comment]
I think we will need to keep those around for V2 to support staggered migration from OAuth1 to OAuth2. -- As in: use legacy constructors to go OAuth1 and use new constructors for OAuth2 . @aarondcoleman thoughts?

**Comment by WestDiscGolf** [comment]
But my understanding was the only thing you could do OAuth1 wise come April will be to switch a 1 token for a 2 token, you'll still need to request resources with a 2 token and hence won't need to spin up a `FitbitClient` with any of the oauth1 handshake / dance ?

**Comment by mxa0079** [comment]
Correct. This is needed between now and April 12th. Another option is to release a V 1.X with all the code from V1 and all the code from V2 (Fitbit and Fitbit.Portable) to aid with the migration, and release V2 with only Fitbit.Portable (the portable would not be needed at this point) after April 12th.

**Comment by mxa0079** [comment]
Closing issue. We need this constructors in V2 to aide with the migration. We will remove them in V3 along with any XML based method.
