### ISSUE TITLE
Rename Authenticator2 to `OAuth2Helper`

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#132]
I am doing end to end testing of the library usage flow, and I believe this name better reflects the purpose of the class. @aarondcoleman @WestDiscGolf thoughts?

**Comment by WestDiscGolf** [comment]
There already is a `OAuth2Helper.cs`? Do you want to move the code into this class or create a new one? Maybe `OAuth2AuthenticatorHelper`?

**Comment by mxa0079** [comment]
Great catch @WestDiscGolf. I think `Autheticator2` and `OAuth2Helper` responsibilities overlap. I will consolidate them into a single class.
