### ISSUE TITLE
Create a Fitbit.Net.OauthMigration package to aide with migration from OAuth1 to OAuth2

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#142]
Here is an idea:

Move all existing functionality related to OAuth1 to a separate package whose responsibility is to ease migration from OAuth1 to OAuth2 (e.g. Fitbit.Net.OauthMigration). This package will depend on Fitbit.Net

Contents of the package:
* `Authenticator`
* All the V1 synchronous methods of `FitbitClient`, implemented as extension methods
* A factory to create an OAuth1 version of  `FitbitClient`

What will be removed from the main package:
*  `Authenticator`
*  All `FitbitClient` constructors marked obsolete -- those are only there to support OAuth1

Advantages:
* Eases migration to OAuth2 (better than today due to the legacy methods implemented as extensions methods to `FitbitClient`) WHILE reducing the surface area of the API
* Allows us to easily remove OAuth1 related code from the library without having to issue a major version in a couple of months
* Removes the obscure behavior of our current constructors  (use obsolete constructor to create an OAuth1 client, use new constructor to create an OAuth2 client), it replaces it with an explicit way to create an OAuth1 version of the client (the factory in the migration package)
* Saves us from carrying forward code that will only be used for the first two months of the library's life

Disadvantages:
* Makes changes to an RC version of the package. However, given that we have had a small number of downloads, I think this is acceptable.

Thoughts?

**Comment by WestDiscGolf** [comment]
Sounds like a plan to me :-)

**Comment by mxa0079** [comment]
=D

**Comment by aarondcoleman** [comment]
Seems like more work than it's worth. Most users I imagine have V1 downloaded locally and I don't think they'll trust a new package to replace what they have, just start moving over stuff to the new library. Efforts better spent elsewhere is my opinion.

**Comment by mxa0079** [comment]
I am also ready to move on to other matters. However, I believe putting the time now will pay off in the future. The flaws in our current approach became very obvious when I started to work on our own migration.

**Comment by mxa0079** [comment]
Ok, I gave myself a 2 hour limit on this. I finished removing all OAuth1 code from main package, and moving it into a migration package. 

However, the extension method idea is more complex that I thought (given the tight dependency on Rest sharp). I will not spend time implementing that.

**Comment by WestDiscGolf** [comment]
10 days later I'm guessing it's done ;-)

**Comment by mxa0079** [comment]
Yeah, I closed the issue this morning. However, I still need to publish the
package to the public feed. Code is in the repo.

On Tue, Mar 1, 2016 at 12:16 PM, Adam Storr <notifications@github.com>
wrote:

> 10 days later I'm guessing it's done ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aarondcoleman/Fitbit.NET/issues/142#issuecomment-190884056>
> .
>



-- 
Mau
Fitabase

**Comment by WestDiscGolf** [comment]
Nice!
