### ISSUE TITLE
2 methods missing XxxXxxAsync convention

### ISSUE THREAD

**Issue by aarondcoleman** [aarondcoleman/Fitbit.NET#144]
`GetApiFreeResponse ` and `RefreshOAuth2Token ` should be: `GetApiFreeResponseAsync` and `RefreshOAuth2TokenAsync` if we're sticking to the convention. Oops!

**Comment by WestDiscGolf** [comment]
Agreed!

**Comment by WestDiscGolf** [comment]
PR #146

**Comment by mxa0079** [comment]
Thanks @WestDiscGolf
