### ISSUE TITLE
Ensure that `FitbitTokenException` provides raw access to wire information

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#169]

**Comment by WestDiscGolf** [comment]
Not clear what this means, can you elaborate?

**Comment by mxa0079** [comment]
@WestDiscGolf Glad to do so. If we get an exception during authentication, we want to ensure that the `HttpRequest` and `HttpResponse` object is accessible through the `FitbitTokenException` exception.
