### ISSUE TITLE
Support .net core

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#175]
Just adding this in for a placeholder for a discussion really; what are peoples thoughts on .net core support?

My initial thoughts are ...

Should we support it: Yes
When: not yet, let's get everything from Microsoft stable and RTM'd first and then we can assess and plan for it.

**Comment by WestDiscGolf** [comment]
As the current .net target framework is 4.5 I believe we can target .Net Standard 1.0 which is good. Still need to check that and look into what is required to make that change though :)

**Comment by AlexGhiondea** [comment]
@WestDiscGolf if you are still considering supporting .NET Core let me know -- I would be happy to help with that.

**Comment by WestDiscGolf** [comment]
Hi, I still think we should but I have been a bit busy. I think it will need to be done through a net standard library and due to the dependency on httpclient I believe it will either need to be netstandard 1.5 or 1.6 (can't remember off the top of my head). To be honest I've read up on netstandard and took a quick go the other week to try and convert it but didn't get very far. I would be interested in hearing your thoughts. I think the most important thing is that the library continues to be functional and usable for @aarondcoleman at fitabase. Due to this it may even have to be netstandard 2 for full .net compatability but I am waiting for .net core 2 / aspnet core 2 / vs 2017 update 3 to come out of preview before investing time to see if that is the case.

**Comment by AlexGhiondea** [comment]
@WestDiscGolf I ran the ApiPort tool on the assembly and the only major dependency (that is not in .NET Standard 1.0) is System.Net.Http. However, there is a package that contains that assembly (that should work).

And even those (System.Net.Http) are available in .NET Standard 1.1.

And, if you are willing to support .NET Standard 1.6 -- then I think the code will just compile for 1.6. with no additional changes (ie. all the APIs used by Fitbit.portable.dll are in .NET Standard 1.6).

If you don't mind, I can take a stab at porting this to .NET Core.

**Comment by WestDiscGolf** [comment]
Sounds reasonable to me. As I said though it comes down to Aaron's requirements for backwards compatability.

Give it a whirl and let's see! I'd be interested in seeing how the conversation works :-)

**Comment by AlexGhiondea** [comment]
@WestDiscGolf I have the project compiling against .NET Standard 1.3 (which maps to [.NET Framework 4.6](https://github.com/dotnet/standard/blob/master/docs/versions.md)). 

The reason for that is `System.Xml.XmlDocument` is only supported starting with .NET Standard 1.3. 

The types needed from that are the ones used to decorate `UpdatedResource` in order to use with the XmlSerializer.

**Comment by AlexGhiondea** [comment]
@WestDiscGolf here is the commit: https://github.com/AlexGhiondea/Fitbit.NET/commit/61aa2999371994e0d3e9d15ad41a95884e1aacb0 

There were a couple of small code changes that were required (around reflection).

**Comment by AlexGhiondea** [comment]
I got the test working (the ones that don't use the attribute for the expected exception) and they all pass when running against the netCore version.

The only question I have for @aarondcoleman or @WestDiscGolf is which version of .NET Framework you want to target? Will 4.6 work?

**Comment by WestDiscGolf** [comment]
@AlexGhiondea We shouldn't be needing the XmlDocument as everything should be json. The only reference I recall (not explicitly looked) was for the subscription manager which needs converting into using the new format and json data. There are existing items open #81 #148 for this which need looking at to remove this dependency.

**Comment by AlexGhiondea** [comment]
Since that was the only place where the Xml Serializer was used, I submitted a PR to remove that and move over to the json format.

I am not sure if there is still a way to receive xml from Fitbit. If there is, then the PR (#220) is not correct.

**Comment by AlexGhiondea** [comment]
@WestDiscGolf @aarondcoleman in order to support .NET Core there are a couple of things that need to happen (remove the dependency above, update the dependencies to NUnit, fixup the tests, etc).

Would you rather I submit multiple independent PRs for each of those changes or would you rather a single large PR (I would prefer multiple independent ones, but it depends how soon can they get merged).

**Comment by WestDiscGolf** [comment]
As I can't merge I can't say for certain however personally I would say small individual prs are better as long as they are self contained and function by themselves without the others needing to be merged :-)

**Comment by JeffDalby** [comment]
I'm working on adding FitBit support to our Xamarin Forms app, adding .net core support would really help us to avoid having to essentially re-write it. I'd love to help with any testing once available.

**Comment by WestDiscGolf** [comment]
Closing due to implementation in flight
