### ISSUE TITLE
Error when hitting authenticator.ExchangeAuthCodeForAccessTokenAsync code.

### ISSUE THREAD

**Issue by mcappello** [aarondcoleman/Fitbit.NET#180]
I've been trying to get OAuth 2.0 working with the Async calls..  I finally got it to allow me to log in, however, when I try and do a call to get data from the Fibit.Api.Portable.. i'm getting the following error:
 
Searches related to Method System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[Fitbit.Api.Portable.OAuth2.OAuth2AccessToken].AwaitUnsafeOnCompleted: type argument 'Microsoft.Runtime.CompilerServices.TaskAwaiter`1[System.String]' violates the constraint of type parameter 'TAwaiter'.
 
This is from this line of code:
System.Threading.Tasks.Task<Fitbit.Api.Portable.OAuth2.OAuth2AccessToken> accessToken = authenticator.ExchangeAuthCodeForAccessTokenAsync(code);
 
The code parameter is a string.. " b76ede61d0b5e357172d98c6137caf5fcad49415"
 
I'm not sure why this is happening.  Has anyone else had this issue?
 
The Fitbit.Api.Portable can be found on GitHub.
 
any help with this would be great.
Thanks.

**Comment by aarondcoleman** [comment]
Your use of that method is incorrect. The return type isn't `Task` it's `Task<OAuth2AccessToken>` You should await that task unless you plan to group them and to it somewhere else in code.

So instead try using the following line:
`OAuth2AccessToken accessToken = await authenticator.ExchangeAuthCodeForAccessTokenAsync(code);`

**Comment by mcappello** [comment]
Thanks.  Got it working. At least that function...however all the calls to
get data like the async call to get profile data comes back with result =
{not yet computed}.

Do you have any idea why this is happening?

Thanks for any help with this.

Mary Cappello

**Comment by aarondcoleman** [comment]
Hi Mary. My guess is you aren't `await`ing those calls. You might want to do a refresher on async/await in C# 5 as it's a little more complicated an you have to specifically use those keywords to tell .NET when to fire a task, when to save it for computing later.

**Comment by mcappello** [comment]
Hi Aaron:

If i use await on the call it does not work at all, and does not even go
into the Catch Error Section.

When I try and debug, it tells me it's not an awaitable call.

Have you tried to use the call client.GetUserProfileAsync();  in your
projects?

If so..  can you email me the code you used to do the call.

I tried to do it the same way I did the async call for the Auth Token..
 and I get the exact same error.

I figured since you are the main developer for the api.  Possibly you
actually did some code to call the function.

Here is my code for the call of the profile. which gives the error.

   * private async void UserProfile(Fitbit.Api.Portable.FitbitClient
client)*
    {


        try
        {
 * // The remmed out code I was able to get the Error of Result = {}*
*           // System.Threading.Tasks.Task<UserProfile> profile =
client.GetUserProfileAsync();*
*           // This code below would be the async call however it basically
skips out of the function and goes to the next line in the function that
the call to this function happens.*
*            UserProfile profile = await client.GetUserProfileAsync(); *
            UserProfile uProfile = profile; //.Result;
            if (uProfile != null)
            {

                imgProfile.ImageUrl = uProfile.Avatar;
                lblName.Text = uProfile.FullName;
                lblDOB.Text = uProfile.DateOfBirth.Day.ToString() + "/" +
uProfile.DateOfBirth.Month.ToString() + "/" +
uProfile.DateOfBirth.Year.ToString();
                lblGender.Text = uProfile.Gender.ToString();
                lblCity.Text = (string.IsNullOrEmpty(uProfile.City)) ? "NA"
: uProfile.City;
                lblCountry.Text = (string.IsNullOrEmpty(uProfile.Country))
? "NA" : uProfile.Country;
            }
        }
        catch(Exception ex)
        {
            string sErr = ex.Message;
        }
    }


Here is my code for the call of the AuthToken..  which works fine:

   * public async void Callback()*
    {

        var appCredentials = new FitbitAppCredentials()
        {
            ClientId = ConfigurationManager.AppSettings["FitbitClientId"],
            ClientSecret =
ConfigurationManager.AppSettings["FitbitClientSecret"]
        };

        fappCredentials = appCredentials;

//localhost for testing in Visual Studio.
        if (Request.Url.GetLeftPart(UriPartial.Authority) == "
http://localhost:50021")
        {
            var authenticator = new
Fitbit.Api.Portable.OAuth2.OAuth2Helper(appCredentials,
Request.Url.GetLeftPart(UriPartial.Authority) +
"/BookInHealth/ClientView/FitbitInfo.aspx");

            string code = Request.Params["code"];

           //This code works..  the async call for the AuthToken
           * Fitbit.Api.Portable.OAuth2.OAuth2AccessToken accessToken =
await authenticator.ExchangeAuthCodeForAccessTokenAsync(code);*

            ////Store credentials in FitbitClient. The client in its
default implementation manages the Refresh process
            var fitbitClient = GetFitbitClient(accessToken);
          * //This is where the errors occur.*
*            UserProfile(fitbitClient);*
*            HeightWeight(fitbitClient);*
*            ActivitySummary(fitbitClient);*
        }
        else
        {
           //Code for Production.
            var authenticator = new
Fitbit.Api.Portable.OAuth2.OAuth2Helper(appCredentials,
Request.Url.GetLeftPart(UriPartial.Authority) +
"/ClientView/FitbitInfo.aspx");

            string code = Request.Params["code"];

            Fitbit.Api.Portable.OAuth2.OAuth2AccessToken accessToken =
await authenticator.ExchangeAuthCodeForAccessTokenAsync(code);

            ////Store credentials in FitbitClient. The client in its
default implementation manages the Refresh process
            var fitbitClient = GetFitbitClient(sAccessToken);
            UserProfile(fitbitClient);
            HeightWeight(fitbitClient);
            ActivitySummary(fitbitClient);
        }


    }

Any help with this would be great.

Thanks.
Mary Cappello

**Comment by aarondcoleman** [comment]
Hi @mcappello . Yes, we use it all the time at my company. At first glance your first issue is that your method `private async void UserProfile(Fitbit.Api.Portable.FitbitClient
client)` is returning `void` and that's a big no-no in async programming. It should at least return Task so that it can also be awaited by its caller.

I really can't though be supporting your consuming code. Please only file bugs against the library if there is an reproducible issue within this codebase. I'd recommend watching some tutorial videos on C# async / Task Parallel Library; it's a big shift but fundamentally the right approach for this kind of application.

**Comment by mcappello** [comment]
So basically I have to do two functions..  one to bring back the acyn then
one to actually do something with the data.

OK..  will go from there.  Thanks.
Mary

**Comment by mcappello** [comment]
Hi Aaron.

I just wanted to let you know... I got it to work, for the most part.

I did notice that my data is not coming back correctly for things like
weight and height.

My profile has 155 lbs as my weight in Fitbit,
But when I bring it back it says 70.3  which is Kilograms.  Very odd.  But
I'm sure I can find a way to convert Kilograms to lbs.

Thanks so much for all of your help.

Mary Cappello

**Comment by WestDiscGolf** [comment]
@mcappello Hi, you can specify the measurement units in the accept language header -  https://dev.fitbit.com/docs/user/ - which should be able to be done manually through accessing the HttpClient property on the FitbitClient instance.

**Comment by mcappello** [comment]
Thank you Aaron. Your help is much appreciated

Mary
