### ISSUE TITLE
Add missing values to ActivitySummary object

### ISSUE THREAD

**Issue by aarondcoleman** [aarondcoleman/Fitbit.NET#189]
Missing values that now are part of this response are
* `floors`
* `heartRateZones`
* `marginalCalories`
* `caloriesBMR`
* `restingHeartRate`
Most not supported by all devices, will be making them nullable.

**Comment by atbyrd** [comment]
@aarondcoleman Has this been included in any of the released or prereleased nuget versions. I'm trying to access floors right non in RC-3 but it's not available.

**Comment by WestDiscGolf** [comment]
@atbyrd The last nuget release was unfortunately a little while ago and did not include these changes. Cloning the repository and building the latest code should allow you to create the latest code dll which you can drop in :)
