### ISSUE TITLE
Which version of VS needed to build the solution

### ISSUE THREAD

**Issue by AlexGhiondea** [aarondcoleman/Fitbit.NET#219]
Hi

I am trying to build the .NET Portable solution on my machine, but I am running into issues.

What version of VS do you use for that?

Thanks,
Alex

**Comment by amammay** [comment]
@AlexGhiondea i was using VS 17 for when i was doing the sleep api upgrades and it seemed to work fine, what kind of issues are you running into?

**Comment by AlexGhiondea** [comment]
I am getting this:

```
There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\windows\Microsoft.NET\Framework\v4.0.30319\\mscorlib.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

I will try on a different machine as well

**Comment by AlexGhiondea** [comment]
@amammay I think there is something wrong in my machine -- I was able to build it just fine on a different machine.
