### ISSUE TITLE
Cleanup Activity Changes

### ISSUE THREAD

**Issue by dwaynefitabase** [aarondcoleman/Fitbit.NET#228]
Redmorello has made a bulk of the changes but there are some items that need to be cleaned up. Changes are needed ASAP so going to make changes from this branch
https://github.com/aarondcoleman/Fitbit.NET/pull/198

**Comment by amammay** [comment]
https://github.com/aarondcoleman/Fitbit.NET/pull/222/files

It would be worth to look into the pull request i made when i did the sleep api unit testing. Specfically the Pagination object gets a proper DataTime object and not a string.
