### ISSUE TITLE
Ability to GET and SET Weight goals

### ISSUE THREAD

**Issue by timfitabase** [aarondcoleman/Fitbit.NET#248]
The ability to get and set weight goals is not currently covered.

**Comment by WestDiscGolf** [comment]
Looks like it would be an extension to `SetGoalsAsync` although the api for this method is not ideal it is what we currently have for setting goals :)

We don't have any "get" goals specifically but you do get them after the `POST` so I'd imagine there is a resource uri somewhere for it.
