### ISSUE TITLE
WeightLog Time is always 23:59:59 // SetWeight

### ISSUE THREAD

**Issue by LouisMehring** [aarondcoleman/Fitbit.NET#265]
The GetWeigth Method returns always 23:59:59 for the time of the Log no matter if I track the time on the Website or via the FitBit App. 
Is there an issues with the API or is it a Fitbit Problem? 
I know https://dev.fitbit.com/build/reference/web-api/body/ says its this time if the time is not provided but is there a option to Log the time aswell. 
This leads me to my second question is there a function planned for setWeight for a specific day / or in general? 
Thanks in Advance for your awesome work!

**Comment by aarondcoleman** [comment]
Hi!

In the Fitbit app a manual weight entry is set by the user only with they day/date. Our library mirrors the Fitbit API implementation and uses that time. If a user steps on a connected weight scale then a time part is included. So this is one way we can infer if the weight was manual or device-created.

As for SetWeight, I’d welcome a pull request to add it. To do that, make a new issue that just describes that and we can build off of that.

Cheers,
Aaron
