### ISSUE TITLE
Deprecate unsupported HR features

### ISSUE THREAD

**Issue by brittanyFitabase** [aarondcoleman/Fitbit.NET#283]
It has come to our attention that Heart Rate Time Series v1.1 is not supported by Fitbit, nor are detail-levels of "15min" or "1y".  We need to deprecate methods that use v1.1 and the enum values for those detail levels, and add methods using v1 of the API.  The deprecated methods will soon sunset.

**Comment by ian-gavurin** [comment]
Is this still the case for the detail levels?
Some of them still seem to be valid?

HeartRate for example: Current documentation lists 15min  as supported, and when I call the API directly it seems to work?
