### ISSUE TITLE
Missing Api Calls and Data

### ISSUE THREAD

**Issue by ChrisTasatzis** [aarondcoleman/Fitbit.NET#326]
Missing API Call
- [Get Heart Rate Time Series by Date Range ](https://dev.fitbit.com/build/reference/web-api/heartrate-timeseries/get-heartrate-timeseries-by-date-range/)

Missing Data For
- [Get Sleep Log by Date](https://dev.fitbit.com/build/reference/web-api/sleep/get-sleep-log-by-date/)
  1. endTime
  2. infoCode
 
- [Get Devices](https://dev.fitbit.com/build/reference/web-api/devices/get-devices/)
  1. batteryLevel

**Comment by aarondcoleman** [comment]
@ChrisTasatzis thanks for this PR! We'll take a look and evaluate the work shortly.
