### ISSUE TITLE
Breaking Changes Moving to Async

### ISSUE THREAD

**Issue by aarondcoleman** [aarondcoleman/Fitbit.NET#35]
Here's the deal -- this is an HTTP plumbing library and .NET introduced the "async" modifier since to allow for clever thread repurposing while things like HTTP and / IO are waiting for responses. Microsoft and the .NET OSS community have also made great progress in Portable Class Libraries (PCL) which are common denominator projects that can span all the subset .NET frameworks (Windows Phone 8, Xamarin, Silverlight, etc). Not everyone is down with async yet either in the .NET community, there's a slight learning curve.

If I were to start this library over again from scratch I'd 

1) Not use restsharp as it isn't PCL compatible (but a small stalled branch is) and doesn't use the async modifier (though it has an older style async callback structure).

2) Not consume the XML endpoints from Fitbit as the JSON ones seem to get a little more love from their API team and on several occasions malformed XML with debug data has caused issues. Plus, everyone loves JSON.net and serialization/deserialization speed.

We have some ideas on how to start to move to this, but it likely means breaking changes or a non PCL. I for one would like to start using async versions of parts of the client library right away in parts of my project that are most frequently called (GetUserProfile, TimeSeries, and DailyActivity) but cannot in one swoop replace all the methods.

So, I'm open to ideas. We might continue a long branch offshoot so we can make progress in both, we might merge the projects with a common project where sync and async/pcl live, and we might just say screw it and start an entirely new project. 

Myself and @WestDiscGolf have already started exploring technically how to do this. See:
* https://github.com/WestDiscGolf/Fitbit.NET/tree/Sans-RestSharp (Adam's latest with JSON attributes on model and using AsyncOAuth)
* https://github.com/aarondcoleman/Fitbit.NET/tree/portable-async (my PCL using AsyncOAuth but relying on the PCL branch of Restsharp)

Chime in with feedback.
--Aaron

**Comment by WestDiscGolf** [comment]
Changed the way to mock the handlers for unit testing the new FitbitClient, updated/added some further testings including the SetGoalsAsync tests and merged/migrated the Water PR from November (https://github.com/aarondcoleman/Fitbit.NET/pull/39).

Latest - https://github.com/WestDiscGolf/Fitbit.NET/

**Comment by aarondcoleman** [comment]
Closing this as we've already established the breaking changes are imminent.
