### ISSUE TITLE
OAuth 2.0 Support?

### ISSUE THREAD

**Issue by danielsomers** [aarondcoleman/Fitbit.NET#41]
Hi,

I was reading the [Fitbit API docs](https://wiki.fitbit.com/display/API/Fitbit+API) and it says their new devices, Charge, Charge HR, and Surge, will only be supported though OAuth 2.0 endpoints. Also it says they're planing to transition to OAuth 2.0 in the coming months.

My question is, do you have plans to support OAuth 2.0 in this project?

Thanks for all the work you've already done on this very useful project.

Regards,

Daniel

**Comment by WestDiscGolf** [comment]
Hi Daniel,

The new data types will be available through oauth 2 only but the current end points, which haven't been deprecated, will still be accessible through oauth 1 at the moment. Aaron and I have been talking about the oauth 2 support and will be looking to incorporate that and the new endpoints into the v2 pcl version of the library we're currently working on.

Hope that answers your question :-)

**Comment by danielsomers** [comment]
Thanks for your answer.

Just to clarify, does that means I'd be able to get an old data type, like steps, from one of Fitbit's new devices, like the Charge, through the old OAuth 1 endpoint?

Thanks again.

Daniel

**Comment by WestDiscGolf** [comment]
As far as I am aware yes but while it's not been released and further details haven't made it out to the public yet I can't fully confirm; Aaron?

**Comment by aarondcoleman** [comment]
@danielsomers yes, that's correct. We're doing that now. It's only the new types of data, like HeartRate that'll be restricted to the OAuth 2.0 endpoints. My understanding is that there will be plenty of time for folks to migrate code and continue to authenticate via OAuth 1.0a. When you're ready they'll also have an API endpoint to exchange your OAuth 1.0 tokens for 2.0. 

Our plans with this library have been to allow that migration to happen incrementally as well. So, for example, Adam and I have been deliberate to not cause any namespace collision when using the newer version we're working on and the old version. The idea being is that you'll probably incrementally start subbing out places in code that you use the old synchronous  / xml / 1.0a calls, for places that use the async / 2.0 / json based ones.

**Comment by danielsomers** [comment]
Thanks so much Aaron.

That's exactly what I needed to know.
