### ISSUE TITLE
Azure WebApi Unauthorized

### ISSUE THREAD

**Issue by freeubi** [aarondcoleman/Fitbit.NET#42]
I just put into the Azure WebApi2 project, and call:

   FitbitClient client = new FitbitClient("824d4b38500e4b90bd02655c29338e93",
             "82...........",
             currentUser.fitbit_oauthtoken,
             currentUser.fitbit_oauthsecret);

            Activity dayActivity = client.GetDayActivity(new DateTime(2015, 2, 1));

then i got "Http Error:Unauthorized" on the getDayActivity call.
Any idea why?

**Comment by WestDiscGolf** [comment]
Has your "currentUser" been authenticated? Have they logged in and retrieve their oauthtoken and secret? Check with the debugger and make sure the values you've got when authenticated are being read back out and being passed into the FitbitClient, what do you find?

With the limited information supplied I'm unable to help much more than the suggestions above, sorry.

**Comment by freeubi** [comment]
Yes, i can get data on windows phone. I authenticate there, then store the token and token secret.

**Comment by WestDiscGolf** [comment]
After authenticating with fitbit on the windows phone how are you saving the token/key on the server? How are you authenticating between the windows phone and the webapi?

There's only so many debugging ideas/checks I can think of with the limited information provided and no details of the bigger picture :-(

**Comment by freeubi** [comment]
I just store in a azure database, and read from the webapi.

**Comment by WestDiscGolf** [comment]
How does the webapi code know who is calling it? How does it know who the "currentUser" is? How is the client (windows phone in this case) identified to the api call?

**Comment by freeubi** [comment]
I pass the userid to the webapi call, then make a database query and use that user accesstoken and tokensecret.

**Comment by WestDiscGolf** [comment]
Can you access other fitbit api calls eg. current user profile with this method?

**Comment by freeubi** [comment]
No, i got the error with every call.
Forgot to mention, the service is hosted on localhost currently.

**Comment by WestDiscGolf** [comment]
If you hard code the oauth token/secret for the user does it work? If you hard code the call in an MVC action or a standalone console app does it work?

**Comment by aarondcoleman** [comment]
localhost shouldn't matter. BTW, I just modified your comment to remove your OAuth secret key. Don't share that publicly, not that they're hard to come by, but someone else could get yours booted if they used it maliciously.

**Comment by WestDiscGolf** [comment]
I've put together a prototype to try and answer your question. It goes to get fitbit data from the web api doing the following:

1) Add additional properties onto the application user

    public class ApplicationUser : IdentityUser
    {
        public string FitbitOAuthToken { get; set; }

        public string FitbitOAuthSecret { get; set; }

        public string FitbitUserId { get; set; }

       // snip
    }

2) Create an action which directs to fitbit (as per configured at fitbit.com). This is the sample code from the repository in the Sample Web MVC.

        [Route("fitbit")]
        public ActionResult Authorize()
        {

            //make sure you've set these up in Web.Config under <appSettings>:
            string ConsumerKey = ConfigurationManager.AppSettings["FitbitConsumerKey"];
            string ConsumerSecret = ConfigurationManager.AppSettings["FitbitConsumerSecret"];


            Fitbit.Api.Authenticator authenticator = new Fitbit.Api.Authenticator(ConsumerKey,
                                                                                    ConsumerSecret,
                                                                                    "http://api.fitbit.com/oauth/request_token",
                                                                                    "http://api.fitbit.com/oauth/access_token",
                                                                                    "http://api.fitbit.com/oauth/authorize");
            RequestToken token = authenticator.GetRequestToken();
            Session.Add("FitbitRequestTokenSecret", token.Secret.ToString()); //store this somehow, like in Session as we'll need it after the Callback() action

            //note: at this point the RequestToken object only has the Token and Secret properties supplied. Verifier happens later.

            string authUrl = authenticator.GenerateAuthUrlFromRequestToken(token, true);
            return Redirect(authUrl);
        }

3) Setup the callback action

        [Route("fitbit/callback")]
        public async Task<ActionResult> Callback()
        {
            RequestToken token = new RequestToken();
            token.Token = Request.Params["oauth_token"];
            token.Secret = Session["FitbitRequestTokenSecret"].ToString();
            token.Verifier = Request.Params["oauth_verifier"];

            string ConsumerKey = ConfigurationManager.AppSettings["FitbitConsumerKey"];
            string ConsumerSecret = ConfigurationManager.AppSettings["FitbitConsumerSecret"];

            //this is going to go back to Fitbit one last time (server to server) and get the user's permanent auth credentials

            //create the Authenticator object
            Fitbit.Api.Authenticator authenticator = new Fitbit.Api.Authenticator(ConsumerKey,
                                                                                    ConsumerSecret,
                                                                                    "http://api.fitbit.com/oauth/request_token",
                                                                                    "http://api.fitbit.com/oauth/access_token",
                                                                                    "http://api.fitbit.com/oauth/authorize");


            //execute the Authenticator request to Fitbit
            AuthCredential credential = authenticator.ProcessApprovedAuthCallback(token);

            //here, we now have everything we need for the future to go back to Fitbit's API (STORE THESE):
            //  credential.AuthToken;
            //  credential.AuthTokenSecret;
            //  credential.UserId;

            var user = UserManager.FindById(User.Identity.GetUserId());
            user.FitbitOAuthSecret = credential.AuthTokenSecret;
            user.FitbitOAuthToken = credential.AuthToken;
            user.FitbitUserId = credential.UserId;

            var result = await UserManager.UpdateAsync(user);

            return RedirectToAction("Index", "Home");
        }

Note: the await on the UserManager.UpdateAsync is important!

4) Now add a web api controller to return the data you required

    public class FitbitController : ApiController
    {
        private ApplicationUserManager _userManager;

        // GET api/fitbit
        public object Get()
        {
            string ConsumerKey = ConfigurationManager.AppSettings["FitbitConsumerKey"];
            string ConsumerSecret = ConfigurationManager.AppSettings["FitbitConsumerSecret"];

            var user = UserManager.FindById(User.Identity.GetUserId());

            var fitbit = new FitbitClient(ConsumerKey, ConsumerSecret, user.FitbitOAuthToken, user.FitbitOAuthSecret);

            var data = fitbit.GetDayActivity(new DateTime(2015, 3, 1));
            return Json(data);
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
    }

5) Now run the application and register a user, login and go through the redirect to fitbit to get the authorisation tokens.

**Comment by freeubi** [comment]
Thank you, thats gonna be a big help. I will try out soon :)
(I just started to developing the Jawbone in the same way, and that seems to work)

**Comment by freeubi** [comment]
I tried the code, and its not working, when i try to reach any data then i still got "Http Error:Unauthorized" -> but the authentication works.

- i dont have ApplicationUserManager in the webapi 2 class
- the mobileservice is not published, i'm using the localhost iss server.
- i have put all the authentication code to the web api (as you do), its working, i got the token, tokensecret and encoded user id.
Small change that i cant do any redirect, so i just sending back the auth url to the mobile device and making the fibit login there.
- i use my own user object, not the mvc-s : i dont have mvc website, but i dont think that its causing the problem.
-also, i'm hard-coded the fitbit consumer key and consumer secret

All the code below are in the same
public class testsController : ApiController
{

Response class (to contains the data):
```
public class TestFitbitauth
    {
        public string FitbitRequestTokenSecret { get; set; }
        public string  Url { get; set; }
    }
}
```
First authentication get:
```
 public TestFitbitauth Get()
        {
            //first request from mobile
            string ConsumerKey = "-";
            string ConsumerSecret = "-";

            Fitbit.Api.Authenticator authenticator = new Fitbit.Api.Authenticator(ConsumerKey,
                                                                                    ConsumerSecret,
                                                                                    "http://api.fitbit.com/oauth/request_token",
                                                                                    "http://api.fitbit.com/oauth/access_token",
                                                                                    "http://api.fitbit.com/oauth/authorize");
            RequestToken token = authenticator.GetRequestToken();      

            string authUrl = authenticator.GenerateAuthUrlFromRequestToken(token, true);

            TestFitbitauth response = new TestFitbitauth();
            response.FitbitRequestTokenSecret = token.Secret.ToString();
            response.Url = authUrl;        

            //return the authentication url and the token secret
            return response;
        }
```
Second authentication call (after fitbit login on mobile)
```
 public async Task<string> Get([FromUri]string inputstring)
        {
            //On mobile: after fitbit login call this function with token, token secret, verifier and userid
            string token = "";
            string secret = "";
            string verifier = "";
            string userid = "";

            token = TruncateLongString(inputstring, 0, 32);
            secret = TruncateLongString(inputstring, 33, 32);
            verifier = TruncateLongString(inputstring, 66, 26);
            userid = TruncateLongString(inputstring, 93, inputstring.Length-93);


            RequestToken requestToken = new RequestToken();
            requestToken.Token = token;
            requestToken.Secret = secret;
            requestToken.Verifier = verifier;

            string ConsumerKey = "-";
            string ConsumerSecret = "-";


            //create the Authenticator object
            Fitbit.Api.Authenticator authenticator = new Fitbit.Api.Authenticator(ConsumerKey,
                                                                                    ConsumerSecret,
                                                                                    "http://api.fitbit.com/oauth/request_token",
                                                                                    "http://api.fitbit.com/oauth/access_token",
                                                                                    "http://api.fitbit.com/oauth/authorize");


            //execute the Authenticator request to Fitbit
            AuthCredential credential = authenticator.ProcessApprovedAuthCallback(requestToken);

            //get the current user
            Tep_dbEntities entities = new Tep_dbEntities();
            var currentUser = entities.User.Where(x => x.id == userid).Take(1).ToList().FirstOrDefault();

            //(re)write the authentication data
            currentUser.fitbit_encoded_userid = credential.UserId;
            currentUser.fitbit_oauthsecret = credential.AuthTokenSecret;
            currentUser.fitbit_oauthtoken = credential.AuthToken;     

            //save to the db
            await entities.SaveChangesAsync();

            return "0";

            // trying to reach data here, i got Http Error:Unauthorized
            //var fitbit = new FitbitClient(ConsumerKey, ConsumerKey, currentUser.fitbit_oauthtoken, currentUser.fitbit_oauthsecret);
            //var blooom = fitbit.GetDayActivitySummary(new DateTime(2015, 02, 25));

        }
```
After successful authentication the mobile can call this:
```
 public bool Get(string userid, int dayofyear)
        {
            //if the last response is "0", then the mobile calling this
            string ConsumerKey = "-";
            string ConsumerSecret = "-";

            Tep_dbEntities entities = new Tep_dbEntities();
            var currentUser = entities.User.Where(x => x.id == userid && !string.IsNullOrEmpty(x.fitbit_oauthtoken)).Take(1).ToList().FirstOrDefault();

            var fitbit = new FitbitClient(ConsumerKey, ConsumerKey, currentUser.fitbit_oauthtoken,currentUser.fitbit_oauthsecret);

            //var data = fitbit.GetDayActivity(new DateTime(2015,2,1)); -> Http Error:Unauthorized
            //var user = fitbit.GetUserProfile(currentUser.fitbit_encoded_userid); -> Http Error:Unauthorized

            //i have valid data on this day
            var blooom = fitbit.GetDayActivitySummary(new DateTime(2015,02,25)); -> Http Error:Unauthorized
            return true;
        }
```
}

**Comment by freeubi** [comment]
Update:
Today (my first thing lol) i tried to reach the data with the credentials using RestClient. It works.
Here is my updated code (this is the last Get)
```
 public bool Get(string userid, int dayofyear)
        {
            //if the last response is "0", then the mobile calling this
            string ConsumerKey = "-";
            string ConsumerSecret = "-";

            //Get the user data
            Tep_dbEntities entities = new Tep_dbEntities();
            var currentUser = entities.User.Where(x => x.id == userid && !string.IsNullOrEmpty(x.fitbit_oauthtoken)).Take(1).ToList().FirstOrDefault();

            //var fitbit = new FitbitClient(ConsumerKey, ConsumerKey, currentUser.fitbit_oauthtoken,currentUser.fitbit_oauthsecret);


            ////var data = fitbit.GetDayActivity(new DateTime(2015,2,1));
            ////var user = fitbit.GetUserProfile(currentUser.fitbit_encoded_userid);

            ////i have valid data on this day:
            //var blooom = fitbit.GetDayActivitySummary(new DateTime(2015,02,25));


            string apiCall;
            var client3 = new RestClient("https://api.fitbit.com/");

            string getdatestring = DateTime.UtcNow.Year.ToString().ToUpper() + "-" +
                                   DateTime.UtcNow.Month.ToString("00").ToUpper() + "-" +
                                   (DateTime.UtcNow.Day - 1).ToString("00").ToUpper();

            apiCall = string.Format("/1/user/" + currentUser.fitbit_encoded_userid + "/activities/date/" + getdatestring + ".json");
     
            client3.Authenticator = OAuth1Authenticator.ForProtectedResource("-", "-", currentUser.fitbit_oauthtoken, currentUser.fitbit_oauthsecret);

            RestRequest request3 = new RestRequest(apiCall);
            request3.RootElement = "user";

            var response5 = client3.ExecuteAsync(request3, response4 =>
            {                

                var user_response = response4.Content;
                Fitbit_Data.RootObject fitbit_result = JsonConvert.DeserializeObject<Fitbit_Data.RootObject>(user_response);

                if (fitbit_result.summary.steps != 0)
                {

                }
               
            });

            return true;
        }
```

I get the summaryzed data in the Fitbit_Data.RootObject. I will test is more later.

**Comment by freeubi** [comment]
It seem solved now.
I just moved the authentication to the web api project (still doing the same thing) and its working now.
I dont know what causing the problem. Strange.

**Comment by WestDiscGolf** [comment]
That does sound strange and without further details about your setup it would be hard to help debug. From a general system architecture note though only passing a user id into a method and getting the authentication data from a db without checking the user calling the method is the id which is being passed in is a bit of a potential security/data protection issue. Getting the id of the user who is authenticated with the service call using User.GetUserId() (I think is the extension method) would be better.
Happy coding! :-)
