### ISSUE TITLE
Concurrent OAuth 1.0a and OAuth 2.0 support in FitbitClient.cs

### ISSUE THREAD

**Issue by aarondcoleman** [aarondcoleman/Fitbit.NET#46]
OK everyone -- let's plan for something we don't actually have our hands on yet but is imminent: The migration to OAuth 2.0. 

From what I understand from Fitbit's plans:
* OAuth 1.0a will continue to work for previous endpoints until a future sunset date
* A Fitbit API endpoint will be established that allows us to exchange OAuth 1.0a tokens for OAuth 2.0 ones
* New endpoints (like heart rate) will only be accessible via OAuth 2.0

In order to assist people who are going to slowly migrate their application over I'd like to keep the following guiding principles in mind for this wrapper library:
* Breaking changes, i.e. changed data params or returns **should** break on compilation time. This gives the devs a chance to really go through and address the changes and be deliberate.
* Old endpoints that will eventually be sunset should be marked [Obsolete] so at least in the IDE they know it's time to start thinking about it.
* We should try to keep as close to the metal of the new HttpClient. 
* The old Fitbit.NET client library (which depends on XML and RestSharp) should be able to be instantiated and used in memory alongside the new one so folks can move from one to the other.

I think Adam and I have hit a lot of these already so far in this branch.

In terms of OAuth 2.0 we have 2 options (or more, seeking input):
1. Modify the FitbitClient constructor to take an authorization class interface that encapsulates the  functionality of adding credentials to the HttpClient header. 
2. Create different FitbitClient constructors, one that uses OAuth 1.0a and one OAuth 2.0 and has different parameter lists and sets the appropriate header type.

For 1. I'm thinking something like:

```csharp
public class OAuth2Authorization : IAuthorization
{
    public override HttpClient AddAuthorizationHeader(HttpClient existingHttpClient, ....)
    {
        //adds in the auth header
    }
}
```

OR for 2.

```csharp
public FitbitClient(string consumerKey, string consumerSecret, string accessToken, string accessSecret) : this(consumerKey, consumerSecret, accessToken, accessSecret, httpClient: null)
{
    // this one calls the private constructor with the params needed for OAuth 1.0A
}

public FitbitClient(string consumerKey, string consumerSecret, string bearerToken) : this(consumerKey, consumerSecret, bearerToken, httpClient: null)
{
    // this one calls the private constructor with the params needed for OAuth 2.0 (one less param)
}
```

Also, this is how simple it should be to add the Authorization component to an HttpClient for OAuth 2.0, but again, I haven't seen the Fitbit implementation yet:

```csharp

//added helper code for OAuth 2.0 header setting
private void SetHttpClientAuthorizationBearerToken(string token)
{
    AuthenticationHeaderValue authenticationHeaderValue = new AuthenticationHeaderValue("Bearer", token);
    this.HttpClient.DefaultRequestHeaders.Authorization = authenticationHeaderValue;
}
```

Seeking input in comments below. Examples of how this was handled elsewhere?

--Aaron

**Comment by jeremiahlee** [comment]
I’d imagine the world where OAuth 1.0a isn’t even an option any more and pick the method that requires the least effort to use. All Fitbit API endpoints will be compatible with OAuth 2 on the first day of availability. There will be a mechanism to convert OAuth 1.0a access tokens into OAuth 2 bearer and refresh tokens.

In option 2, you’d probably also pass the refresh token. Not sure if that complicates that option. You could discern the type of token a few ways. Fitbit will be using JWT for bearer tokens. They’re significantly longer than the current OAuth 1.0a access tokens and contain two periods. The first two segments of JWT can also be decoded as JSON.

Every OAuth 2 request could potentially fail due to the token needing to be refreshed. Ideally, intercepting that response, making the refresh request, storing the updated bearer and refresh tokens, and retrying the original request should happen without the method making the original request needing to care about the token state.

**Comment by aarondcoleman** [comment]
Oh wow. That the token might need to be refreshed opens up a whole new can of worms. We don't enforce a mechanism for storing tokens, so all that stuff needs to bubble up and allow for folks to store those credentials however they like (SQL, Cache, Session, Blob storage, whatever). Currently that part is done in the Authenticator.cs class (https://github.com/aarondcoleman/Fitbit.NET/blob/async-portable/Fitbit.Portable/Authenticator.cs)

You're right though @jeremiahlee that it'd be a huge pain to fail when a token becomes stale. We'd see a ton of try/catch, literally around every single call so that's ugly. 

We do already wrap API calls in a helper method called "HandleResponse<T>" (https://github.com/aarondcoleman/Fitbit.NET/blob/async-portable/Fitbit.Portable/FitbitClient.cs#L730-L752) such that we can catch things like rate limits or general HTTP issues. I wonder if adding some logic in there is the right place to be.

@jeremiahlee -- what's going to be the policy if a token is refreshed and retried, however, the developer hasn't taken the time to re-store this new one and instead continues to pass a refresh token with the stale previous one and we, in this FitbitClient code just keep using the fresh one and disposing? Is that a possible scenario?

My initial instinct is to require this scenario be defined at the time the FitbitClient is created, something like:

```csharp
//abstract interface that the developer would implement
public interface ITokenRefresher
{
    void StoreRefreshedToken(string bearerToken, DateTime expiration, string refreshToken);
}

//example of a developer concretely defining this for their specific data store
public class DatabaseTokenRefresher : ITokenRefresher
{
    public void StoreRefreshedToken(string bearerToken, DateTime expiration, string refreshToken)
    {
        //database calls that overwrite the previous (now stale) bearer token.  
    }
}
```

such that on a new instance of the FitbitClient, this is specified once:

```csharp
DatabaseTokenRefresher dbRefresher = new DatabaseTokenRefresher();
FitbitClient fitbitClient = new FitbitClient(...., dbRefresher);

//a standard call to retrieve data might automatically do the token refresh swap + store it in the DB without the need to handle this explicitly:
var result = await fitbitClient.GetDayActivityAsync(...);
```
but that's just my first pass at this -- more input welcomed. @WestDiscGolf @jeremiahlee ?

**Comment by jeremiahlee** [comment]
> what's going to be the policy if a token is refreshed and retried, however, the developer hasn't taken the time to re-store this new one and instead continues to pass a refresh token with the stale previous one and we, in this FitbitClient code just keep using the fresh one and disposing? Is that a possible scenario?

When the refresh token is used, a new bearer token and refresh token is returned. Refresh tokens are intentionally fragile. They can only be used once and only get transmitted once. If a second attempt to refresh the bearer token is made with the same refresh token, the refresh request will fail.

**Comment by WestDiscGolf** [comment]
I assume that the re-authed response from using the refresh token will provide another one to use again later though so we can store that? So if we do that we only need to store the refresh token until it's used and then refreshed with the next one and the JWT which will be passed into the authorization header on each request to the api end points. So it breaks down into two (ish) parts:

1) Getting the JWT and adding it to the request header,

2) Using the refresh token to get a JWT (and continue through (1)) if a response back is unauthorized (confirm with fitbit?)

On initial read of the discussion I like the idea of having the storage hidden behind an interface in the core project as the core project shouldn't rely on an external dependancies. We can then let the implementer choose their strategy and/or create some additional projects/nuget packages with other implementations so it's "plug 'n' play" for developers. I also think it needs to be a bit more modular to allow for testing etc.

Will have a think and get back to you

**Comment by kehollin** [comment]
Just found another bit that will need an update here: https://github.com/aarondcoleman/Fitbit.NET/wiki/Subscribing-to-Fitbit-Events

**Comment by kehollin** [comment]
RE: automatic refresh, can it be made optional? I haven't thought it all the way through yet, but in my Jawbone API stuff I'm writing an component that will run daily and explicitly update any tokens for within n days of expiring, and only for "active" participants. So maybe allow null for the iTokenRefresher and bubble up expired token errors when it's null?

**Comment by WestDiscGolf** [comment]
I guess it comes down to how quickly they will expire - @jeremiahlee? I'd imagine there will be no "core" implementation of ITokenRefresher (or whatever it will be called) and the null or failure or whatever will bubble up ... as per if the token refresher failed?!

**Comment by kehollin** [comment]
OK, so maybe I shouldn't have used Jawbone as an example. From the OAuth2 spec:

 ... The authorization code MUST expire
         shortly after it is issued to mitigate the risk of leaks.  A
         maximum authorization code lifetime of 10 minutes is
         RECOMMENDED.  The client MUST NOT use the authorization code
         more than once.  If an authorization code is used more than
         once, the authorization server MUST deny the request and SHOULD
         revoke (when possible) all tokens previously issued based on
         that authorization code.  The authorization code is bound to
         the client identifier and redirection URI.

The single-use bit seems like overkill to me, but it is from the horse's mouth. Maybe we actually want to code it as a single-use? (BTW, I'm happy to apply the outcome of all this to the Jawbone API as time allows.)

**Comment by aarondcoleman** [comment]
Yeah, the more I think about it I think it has to be optional, but highly encouraged. So, if you pass a null for the ITokenRefresher (you didn't implement one, and didn't pass it in) then if that call fails with the current token, it won't retry but instead bubble up an error.

Though unlikely, one scenario is if you had a platform that was both web and mobile, and the mobile app is dependent on some coordinated key sharing, you wouldn't want the mobile app to do the refresh when maybe it doesn't complete the step to phone it home. In this scenario, maybe the failure is acceptable locally, but not on the web server, where you'd implement a refresh and then pass that down to the mobile when a connection was next established.

So, back to my constructor questions at the top of this thread -- that long list of string params is starting to bug me. OAuth 2 credentials are going to contain a bearer token, a refresh token, and an expiration. I'll be curious what info is encoded in the JWT (I'm guessing scope and issue date at least) so that might also be something we wrap with managed code and expose as a property as well. 

Let's see how that looks, shouldn't be long now. Everyone keep mulling it over in terms of the right breakdown.

**Comment by jeremiahlee** [comment]
We're still debating the lifetime of the tokens, but 10 minutes is most likely for the OAuth 2.0 Authorization Code Grant flow.

**Comment by WestDiscGolf** [comment]
@jeremiahlee 10 mins for the Authorization header before you need to use the refresh token to get a new one? Been wondering on what timespan is recommended for this type of thing, I was thinking along the lines of 15 mins so wasn't too far out :)

**Comment by WestDiscGolf** [comment]
@aarondcoleman Thinking along the lines of the signature change; the version which we've created in the async world only has those parameters and overloads (and madness) as it was trying to keep compatibility with the v1 version. If things are going to change dramatically and have breaking changes anyway would it not potentially be a good time to change the signature if we need to?

**Comment by aarondcoleman** [comment]
I don't think we have to keep the constructor signature the same from the old library to the new one. What we do need to keep is the ability for an established platform *ehem, mine* to use both the existing library and the new one without namespace collision as we slowly migrate over. What I'll do is 

1. include both libraries in the project
2. migrate all the endpoints to use the async/portable (and mark all parent methods as async), but continue to use the OAuth 1.0 tokens.
3. exchange all OAuth 1 for OAuth 2 tokens and be off to the races.

It'll take some time. We might write some conditional code that for certain projects keeps the 1.0A tokens that are about to end, and/or start off new projects with 2.0. Hence, it's really 3 different "new FitbitClient(...)" possibilities.

**Comment by jeremiahlee** [comment]
Revision to my previous comment: we're going to launch with a 60 minute access token lifetime.

**Comment by WestDiscGolf** [comment]
Just read https://wiki.fitbit.com/display/API/OAuth+2.0 and it makes sense (which is good). I think the new async client library will need to change quite a bit from the current mechanism, but at least we've got the serilization plumbing for most endpoints in place which is good so it's more the communication layer which needs tweaking.

Just thinking out loud ... personally I think making the new library understand both v1 and v2 oauth journeys natively when one will eventually become unsupported will add additional code and technical debt to the nice new library we're trying to write. On the other hand I completely understand it needs to be functional and work during the transition from one to the other. The mechanism needs to be broken out into separate parts and access token "getting" functionality need to be behind a role interface so the core library has an implementation of it. The core library implementation will be a pure v2 oauth but we can also create an extensions / support library which has a v1a oauth implementation which can be injected in but won't be core code and be removed at a later date from the nuget package (or be in it's own nuget package).

Not sure how exactly it would look at the moment, but initial thoughts on the constructor would be ...

public FitbitClient(ITokenProvider provider /* possibly other dependency interfaces req. */) {}

This would aid with plug and play as well as unit testing. Additional dependencies would probably be the storage mechanism (read / write interfaces) and then other things which are required as we go.

Thoughts?

**Comment by kehollin** [comment]
Would it make sense to have separate clients? Keep FitbitClient as OAuth1.0
and implement 2.0 in a FitbitClient2? That would allow a non-breaking
upgrade, no?

**Comment by WestDiscGolf** [comment]
It's in a different namespace already so it wouldn't make much difference from a naming point of view. It does come down to a migration point of view though. I think making the new async version oauth 2 only would be fine, but due to the way I think it should be architected it wouldn't be much more work implementing a oauth 1a version of the token requester (or whatever it's called) in a separate project for people to use while migrating.

**Comment by kehollin** [comment]
As long as I could drop it into my solution and not break anything I'd be
happy.

**Comment by WestDiscGolf** [comment]
My current issue is that the implementation still assumes there is a redirect url and the consuming code is web based; I'd like to see a method of submitting a username/password key value pair and getting an authorisation response back - @jeremiahlee is there currently a way or is this coming?

**Comment by WestDiscGolf** [comment]
I've also tried to posted a similar question on the fitbit community dev forum as well but it would not submit :(

"Looking at the information about the oauth 2 implementation it still seems to require a redirect to url. Have I understood that correctly?
 
Ideally I would expect the user to be able to pass username and password somehow, possibly in the Authorization header with the BASIC scheme, to avoid having to go to a url and be able to use the oauth method without a browser.
 
Or is this not possible?"

**Comment by aarondcoleman** [comment]
So, I think we need both because of migrations. For Fitabase we need to do
OAuTh transition separate from async. I have a proposed solution in mind.
I'll do a PR and we can discuss.

It's against the princines of OAuth for a client app to ever posses
username / pass. Those should always be directly I putted in to a Fitbit
page and a token received. For mobile, there's a trick where you use the
embedded browser and watch for a specific returnURL in an event handler and
grab the token, then close the browser. I have an example of that for
Xamarin C# /iOS I can share.

--Aaron

**Comment by WestDiscGolf** [comment]
I'm not saying the client app would have the username/password but the user has to login some how. There is a password grant type to allow for app to api communication with username/password - https://tools.ietf.org/html/rfc6749#section-4.3 - and as communication to the fitbit api is over https now the request/response would be encrypted. I understand though however not all api providers want to allow/implement all grant types so we need to work with what there is. The use of a embedded browser just seems like a bit of a fudge to me.

**Comment by WestDiscGolf** [comment]
@aarondcoleman - I'd be interested in seeing the PR to see what your thoughts on it are :+1:

**Comment by WestDiscGolf** [comment]
Been having a little play and come up with this - https://github.com/WestDiscGolf/Fitbit.NET/tree/breaking-change-spike

All of it is contained in the Fitbit.Portable.Spike project and will need re-working/refactoring later but for a starter/discussion point please let me know what you think. It does not contain any implementation but more structural implementation.

**Comment by aarondcoleman** [comment]
Hey Adam,

Yeah, I think this is pretty inline with what I've been advocating in terms of the two different OAuth Authenticators. 

I'm going to mull over the TokenStore piece. On the one hand, it's a clean way to enforce and allow for some out-of-the-box implementations (like your EF and Raven examples), but on the other hand, we risk creating a library with too many implementation opinions. I do like though the idea that there could be a Fitbit.NET.EF NuGet, etc, so then we're able to put people further down the path to spinning up an app.... HMMMM, something to think about.

Now that OAuth 2.0 is out in the wild (though, the Scope params are still not fully functional and default to existing scope limits) we can test against them. I'm going to take a stab at that, trying to get a working FitbitClient that can be pointed to either the 1.0 or 2.0 endpoints in the next few days.

--Aaron

**Comment by aarondcoleman** [comment]
OK @WestDiscGolf I'm thinking we do need require that ITokenStore because of what @jeremiahlee was talking about previously where any API call might fail needing the refresh to occur, store that, and then retry the original request. I'm working on a branch trying out a working implementation, will publish shortly.

**Comment by JonKragh** [comment]
Hey guys - great library! I'm using it for my Fitness Challenge app Challenge Pals.

I'd like to contribute.  The very first thing I ran into while using the code is I see none of the branches have the refresh implementation for Oath 2.0.  Do any of you have that working yet? Thanks!

**Comment by WestDiscGolf** [comment]
Working on it although personally I've been distracted by family and work recently so haven't worked on it as much as I would have liked :-( I know @aarondcoleman uses the library in his day to day work and is working on the newer version taking into account the oauth 2 functionality so he may have got a working version which hopefully he might share soon :-)

**Comment by JonKragh** [comment]
Thanks so much for the response @WestDiscGolf! I created a utility in my app today to today to wrap retry logic (for any errors) and token refresh logic if the token expired.  I need to write the call to Fitbit to exchange the refresh token for a new one on detection of the expiration and I think this will be complete.

usage:
 var ret = await FitbitRequest<TimeSeriesDataListInt>(fbUser.Token, fbUser.RefreshToken, 
                async (client) => { return await client.GetTimeSeriesIntAsync(ts, DateTime.UtcNow.AddDays(-7), DateTime.UtcNow); });


/// <summary>
        ///     Handles token refresh and retry logic for any unknown errors
        /// </summary>
        private async Task<FitbitResponse<T>> FitbitRequest<T>(string bearerToken, string refreshToken, Func<FitbitClient,
            Task<FitbitResponse<T>>> doCall)
            where T : class
        {
            OAuth2Authorization authorization = new OAuth2Authorization(bearerToken, refreshToken);
            FitbitResponse<T> ret = null;
            FitbitClient client = null;
            var retryCount = 0;
            bool hasResult = false;

            while (retryCount < 10 && !hasResult)
            {
                try
                {
                    client = new FitbitClient(authorization);
                    ret = await doCall(client);

                    // is the token expired?
                    if (ret.Errors != null && ret.Errors.Any(e => e.FieldName == "access_token" &&
                                                                  e.Message != null && e.Message.ToLower().Contains("expired")))
                    {
                        // to do: refresh token

                        // to do: store updated token

                        authorization = new OAuth2Authorization(bearerToken, refreshToken);
                        client = new FitbitClient(authorization);
                        ret = await doCall(client);
                    }

                    if (ret.Success)
                    {
                        hasResult = true;
                    }
                }
                catch
                {
                    // do whatever you want
                }
            }

            return ret;
        }

**Comment by aarondcoleman** [comment]
We'd love a pull request if you get the retry logic in there. I think it's partly though tied in to the need to implement some kind of token storage interface. The reason being is that we don't want to force the developer to have to implement the token refresh on every part of his/her codebase, inevitably forgetting one spot and having it crash in production. 

I don't think we want the arbitrary retry on any error in the library. For instance in our project, Fitabase, we use a distributed queue system so depending on the type of error, like a 429 rate limit error, we have logic that pops it out and puts it on a queue for retry later at a specific time. Catching and handling the specific OAuth 2.0 token refresh though, and then bubbling that up to a handler to do its storage should be part of the library solution.

Thanks for the help! Looking forward to a PR.

**Comment by JonKragh** [comment]
Hey @aarondcoleman thanks for the response!  Great point on the generic retry logic based on the type of error. 

I need to wrap my head around contributing on github :) For now, here is what I did in Gists to get the token refresh morning. 

Some of it could be a stepping stone for a more generic implementation.

I added a RefreshTokenAsync to Authenticator2
https://gist.github.com/JonKragh/d5312023d32425bc4aba

I created a helper "FitbitRequest" function to my project - maybe it should be called "MakeFitbitRequest" since it's a method which handles retry on token expiration (And all errors which may be unwanted).  I have an instance of a new class FitbitToken, which if refreshed duting my call flow - the instance is updated and my call flow can continue with the updated token if say I'm making three calls in a row to Fitbit and it expires sometime in the middle.  The FitbitToken is saving to my own data store when refreshed (so obviously that won't work in a library and would need to be extracted).

https://gist.github.com/JonKragh/33087eed7259675c1d81

Then using it I can do things like this all in sequence and token refresh is completely transparent to my app.

var ret = await FitbitRequest<TimeSeriesDataListInt>(token, 
                async (client) => { return await client.GetTimeSeriesIntAsync(TimeSeriesResourceType.MinutesVeryActiveTracker, DateTime.UtcNow.AddDays(-7), DateTime.UtcNow); });

var ret2 = await FitbitRequest<IntradayData>(token,
                async (client) => { return await client.GetIntraDayTimeSeriesAsync(IntradayResourceType.CaloriesOut, DateTime.Now.Date, TimeSpan.FromHours(24)); });

**Comment by jeremiahlee** [comment]
> @WestDiscGolf [commented on May 9](https://github.com/aarondcoleman/Fitbit.NET/issues/46#issuecomment-100543236)
> My current issue is that the implementation still assumes there is a redirect url and the consuming code is web based; I'd like to see a method of submitting a username/password key value pair and getting an authorisation response back - @jeremiahlee is there currently a way or is this coming?

Fitbit has no plans to ever allow third-party applications to handle user name and passwords. The security risk would be too significant. Also, many users use social network sign in to authenticate and new forms of authentication may be offered in the future.

**Comment by WestDiscGolf** [comment]
> @jeremiahlee commented 9 hours ago
>> @WestDiscGolf commented on May 9
>> My current issue is that the implementation still assumes there is a redirect url and the consuming code is web based; I'd like to see a method of submitting a username/password key value pair and getting an authorisation response back - @jeremiahlee is there currently a way or is this coming?

> Fitbit has no plans to ever allow third-party applications to handle user name and passwords. The security risk would be too high. Also, many people use social network sign in to authenticate and new forms of authentication may be offered in the future.

Thanks for the clarification :-)

**Comment by aarondcoleman** [comment]
I'm trying to make progresso on this but I'm beginning to doubt there is an elegant solution to support both OAuth 1.0, 2.0, and also provide 2.0 the unique ability to do the token refresh when it encounters a stale one. The token refresh part I implemented as a singleton repository pattern, like so:

```csharp

public interface IOAuth2AccessTokenRepository
{
    //presumably some concrete implementation will implement a constructor with an id schema

    void Add(OAuth2AccessToken accessToken);

    void Update(OAuth2AccessToken accessToken);
        
    void Delete();

    OAuth2AccessToken Get();
}
```
and an example implementation just using a web Session var here:

```csharp

public class SessionOAuth2AccessTokenRepository : Fitbit.Api.Portable.IOAuth2AccessTokenRepository
{
    HttpContextBase _httpContext = null;
    internal string _tokenId = null;
    public SessionOAuth2AccessTokenRepository(string tokenId, HttpContextBase currentContext)
    {
        if (currentContext == null)
            throw new ArgumentNullException("You must provide the current HttpContext to save session data");

        if (string.IsNullOrWhiteSpace(tokenId))
            throw new ArgumentNullException("You must provide an ID that this session will use to track");

        _httpContext = currentContext;
        _tokenId = tokenId;
    }

    public void Add(Fitbit.Api.Portable.OAuth2AccessToken accessToken)
    {
        _httpContext.Session[_tokenId] = accessToken;
    }

    public void Update(Fitbit.Api.Portable.OAuth2AccessToken accessToken)
    {
        _httpContext.Session[_tokenId] = accessToken;
    }

    public void Delete()
    {
        _httpContext.Session.Remove(_tokenId);
    }

    public Fitbit.Api.Portable.OAuth2AccessToken Get()
    {
        return (Fitbit.Api.Portable.OAuth2AccessToken)_httpContext.Session[_tokenId];
    }
}

```
So that part I feel ok about. You can imagine that instead of session one could implement a database store, a cache store, etc and the library won't care the concrete implementation, just run it.

BUT, then when it's time to set up an actual use of the library and we want to use all the parts, I now have this:

```csharp
SessionOAuth2AccessTokenRepository sessionTokenRepo = new SessionOAuth2AccessTokenRepository("AccessToken-Id", this.HttpContext);
OAuth2Authorization authorization = new OAuth2Authorization(sessionTokenRepo);
FitbitClient client = new FitbitClient(authorization, sessionTokenRepo);
```

The ugliness is a result of the FitbitClient trying to be too flexible. In one incarnation, it takes the previous version of just the OAuth 1.0 access token, client secret, etc, in another it takes just OAuth 1.0 credentials (implemented in the new IAuthorize interface), and in another it takes both an IAuthroize implementation for OAuth 2.0 PLUS the unique ability to re-refresh a token using the IOAuth2AccessTokenRepository pattern, then retry the call to succeed.

I do however want to continue to support 1.0 as we, at Fitabase, need to make the migration slowly as some of our existing customers will finish using 1.0 credentials and others will start on 2.0. So, I'm thinking maybe of ditching IAuthorize and just doing 2 constructors, one if you're going to do old-school styled OAuth 1.0 setup, the other for 2.0 with the required stuff there. 

We could actually just do both by having the following two constructors

```csharp

//assume you're doing OAuth 1.0
public FitbitClient(string consumerKey, string consumerSecret, string accessToken, string accessSecret)
{
   //concretely sets up the OAuth 1.0 logic previously passed in for IAuthoraztion (OAuth1Authorization)
}

public FitbitClient(IOAuth2AccessTokenRepository, HttpClient httpClient = null)
{
      //concretely sets up the OAuth 1.0 logic previously passed in for IAuthoraztion (OAuth2Authorization)
      //flags something in the library to also do the token refresh two-step when it tries to hit a resource and gets a stale token error
}
```

Thoughts?

**Comment by jeremiahlee** [comment]
Design for the future. OAuth 1.0a will not be supported by Fitbit indefinitely, so optimize for OAuth 2.0. I think splitting the constructor is a good approach.

**Comment by WestDiscGolf** [comment]
I've been giving this some thought and to be honest I'm not sure the core library should handle the authentication; I think it should handle requests/responses from fitbit only. If we bake authentication and retries etc. into the core library then we're limiting where it can be used and dictating to the consumer how to use it. Why not say "you provide an authenticated <x>* and call the methods on the library"? (* whatever that might be, unsure at the moment). And then throw a set of exceptions as to when things need to be retried or the user is unauthenticated and let the calling logic work out what to do? I'd say we should write "best practices" and "quick start guides" in the documentation and then potentially write a OAuth 1.0a helper library and a OAuth 2.0 helper library which helps with all the handshaking and let the consuming application deal with the rest but keeping them in separate "units" I think would be better. This way we've not got a library trying to support something which is going to go away to the detriment of the new shiney v2.

Thoughts?

**Comment by WestDiscGolf** [comment]
I've been thinking about the library as a whole with everything we've discussed over the past 6-12 months and looking/using other libraries recently it's allowed me to see how others have approached a similar issue and addressed it. I also had an issue with how big the "FitbitClient" class was getting as it was getting too unweilding. So taking all this into account I've had a bit of a play and finally got around to publishing the results. It's a bit raw and the tests project doesn't build but the methods I've implemented work - https://github.com/WestDiscGolf/Fitbit.NET/tree/async-portable-update

It's only a potential idea, so wanted to put it out there before going too far. Let me know what you think.

Cheers

**Comment by aarondcoleman** [comment]
Hey Adam, I had a look and I think we've exhausted this one particular issue thread (concurrent support of OAuth 1 and 2). I'm closing this one and starting another to talk about the FitbitClient's size and maintainability here: https://github.com/aarondcoleman/Fitbit.NET/issues/52

**Comment by WestDiscGolf** [comment]
:+1:
