### ISSUE TITLE
PreRelease NuGet package for async-portable

### ISSUE THREAD

**Issue by deevus** [aarondcoleman/Fitbit.NET#49]
I'm successfully using this as part of a project but it would be much better if I could install a NuGet package for it. 

Thanks for your great work.

**Comment by aarondcoleman** [comment]
Yeah, I can probably get that going. However, we're going to probably introduce some breaking changes soon, mostly for the OAuth 2.0 implementation. See convo here: https://github.com/aarondcoleman/Fitbit.NET/issues/46

**Comment by mxa0079** [comment]
We have a public RC package!

![](https://camo.githubusercontent.com/f2d49e846f55466fe07dce96ec6227919b694f18/68747470733a2f2f33312e6d656469612e74756d626c722e636f6d2f34336536333436316431653366323261343962313864626631353232376131642f74756d626c725f696e6c696e655f6e337431306f5166496831736f6c706a6d2e676966)
