### ISSUE TITLE
Document or Automate AsyncOAuth.OAuthUtility.ComputeHash setup

### ISSUE THREAD

**Issue by deevus** [aarondcoleman/Fitbit.NET#50]
The following line is in the `Global.Asax.cs` file in the portable sample project which is required for any of the remote calls to work:

```
OAuthUtility.ComputeHash = (key, buffer) => { using (var hmac = new HMACSHA1(key)) { return hmac.ComputeHash(buffer); } };
```

This should be documented or automated (if ComputeHash isn't set)

I'm using the async-portable branch

**Comment by aarondcoleman** [comment]
Yeah, we could do a better job of this. Automating it is tricky because it needs to be set on app start but that's in a different spot in code based on the type of app. Suggestions?

**Comment by deevus** [comment]
Could you encapsulate it into the `FitbitClient` class? Before it is required call something like:

```
OAuthUtility.ComputeHash = OAuthUtility.ComputeHash 
    ?? (key, buffer) => { using (var hmac = new HMACSHA1(key)) { return hmac.ComputeHash(buffer); } };
```

**Comment by WestDiscGolf** [comment]
As OAuth 1 support is going to go away pretty quickly and we'll be using the new OAuth 2 way so this might not be an issue in the future. I do agree though we need to improve the documentation, it's on the list! :-)

**Comment by aarondcoleman** [comment]
In a few months when OAuth 2.0 is the only implementation we won't need AsyncOAuth at all, so we'll just let it die then ;-)
