### ISSUE TITLE
Oauth2 token - exchange the old Oauth1 token

### ISSUE THREAD

**Issue by robertneagu** [aarondcoleman/Fitbit.NET#55]
Hi,
There is any support for obtaining Oauth2 token for the already generated oauth1 tokens?

**Comment by aarondcoleman** [comment]
Yes, we need to implement this asap as many people will need to take their old OAuth 1.0 tokens and exchange them once to get on the OAuth 2.0 train. Here's the Fitbit doc area:

https://dev.fitbit.com/docs/oauth2/#migrating-from-oauth-1-0a

**Comment by mxa0079** [comment]
OAuth2 Authentication is now part of the async-portable branch. This includes the basic functionality to exchange an OA1 token for an OA2 token as [described here](https://dev.fitbit.com/docs/oauth2/#migrating-from-oauth-1-0a).

A helper method to do the specific OAuth1 token concatenation may come in a V2.X update.

Closing issue.
