### ISSUE TITLE
FitbitResponse - should it stay or should it go?

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#58]
As part of the initial re-work almost a year ago I added in a `FitbitResponse` - https://github.com/aarondcoleman/Fitbit.NET/blob/async-portable-oauth2implement/Fitbit.Portable/FitbitResponse.cs - as a wrapper around the response to handle the data returned from the api end points to determine the status of the response etc.

What are peoples thoughts on this? Should it be kept? Should the client return the raw model and handle errors differently? How are people handling rate limits and accessing the `Retry-After` http header (https://github.com/aarondcoleman/Fitbit.NET/blob/async-portable-oauth2implement/Fitbit.Portable%2FFitbitResponseExtensions.cs)?

It would be really good to get some feedback from people starting to use the beta PCL v2 library to see where we can improve the usability against the library api surface.

**Comment by aarondcoleman** [comment]
Hey Adam, I've been thinking about this a bit more as well. It's certainly a departure from the previous implementation where we surfaced a FitbitException on error. The result is code that follows the try/catch design. With FitbitResponse, looking for errors would be a method call, followed by requiring the consumer to remember to test if response.success == true.

What else was the thinking behind the FitbitResponse object? I was thinking another feature that'd be nice to have somewhere is the ability to log the raw HTTP returned by Fitbit in the event of wanting to retrace any unexpected behavior from their end. 

If we're going to make another breaking change though we should do this asap! People are wanting a solid OAuth 2.0 implementation.

Thoughts?

**Comment by WestDiscGolf** [comment]
The main reason behind adding a wrapper around the response was to do with how TAP works with an async response and that you can't (or at least couldn't ... might be possible in .net 4.6?!) work with async functionality and include try/catch and throw exceptions due to the nature of the beast. Knowing now what we know we could change the signatures to return `Task<T>` but there would still be issues / design considerations as to how errors are caught and returned to the user. These would be things along the lines of connection issues through to `429` responses for max connections exceeded etc.

**Comment by WestDiscGolf** [comment]
I've had a quick look at lunch and it seems that throwing an exception should be possible. However I am not writing a production application at the moment with the library or migrating from the old one so will look for guidance on how / when to throw the errors and how people are currently wanting to handle errors such as connectivity and the `429` retries I mentioned before.

Once we agree on the API we can get to work on configuring the cranks and the cogs underneath :-)

**Comment by WestDiscGolf** [comment]
Working on a PR for removing it after a skype call with @aarondcoleman and @mxa0079 :-)

**Comment by WestDiscGolf** [comment]
PR Merged. Closing ...
