### ISSUE TITLE
response.Data is null?

### ISSUE THREAD

**Issue by eveko** [aarondcoleman/Fitbit.NET#61]
After geting the project to build. I can't seem to get the amount of steps. I am using the async-portable branch for the o auth 2 app. Authorization goes just fine. But loading the LastWeekSteps returns an null void exception. Specifically the response.data. I am quite sure my fitbit has logged steps every week.

**Comment by WestDiscGolf** [comment]
On brief investigation I get a 403 forbidden with the latest in the async-portable-oauth2implementation. I will need to investigate further later. Thanks for letting us know.

**Comment by WestDiscGolf** [comment]
Found the problem, with OAuth 2 you need to define the scope which you need to access the different end points. The default code in the example projects only specifies `"profile"` where as you require `"activity"` to get the steps. You specify this in `FitbitController` line 40.

Further info can be found - https://dev.fitbit.com/docs/oauth2/#scope

**Comment by aarondcoleman** [comment]
But that's good feedback, that setting scope isn't very straightforward.

**Comment by WestDiscGolf** [comment]
Something to add to the list for documentation. Seems really strange than the scope is split with a space though on a url querystring and not a comma though. Any ideas why fitbit went for that?!

**Comment by mxa0079** [comment]
Question answered.
