### ISSUE TITLE
Ability to log raw HTTP responses - ILogger or ITrafficLogger, or IResponseLogger implementation?

### ISSUE THREAD

**Issue by aarondcoleman** [aarondcoleman/Fitbit.NET#63]
I'm proposing adding in an optional constructor parameter and an interface that would allow a FitbitClient users to log raw HTTP calls / responses. This accomplishes a couple things:

1) Allows easier debugging if you chose to use it since you can go back and find a raw response and see what's actually going on
2) Find bugs or mismatches in this library
3) Might give us a better shot of sticking the landing if you log a raw response with a refreshed token/refresh token, but you on your own end have an error parsing / saving it (like your DB goes down right as you're trying to replace the keys)

Thoughts?

**Comment by mxa0079** [comment]
What about implementing this using [Http Message Handlers] (http://blogs.msdn.com/b/henrikn/archive/2012/04/27/asp-net-web-api-updates-april-27.aspx).

We would need to move away from instantiating httpclient directly, and instead use the httpclientfactory and allow client consumers to provide their own delegates to intercept request/responses for logging purposes.

**Comment by WestDiscGolf** [comment]
I like the idea, however `HttpClientFactory` is only in the `Microsoft.AspNet.WebApi.Client` nuget package which is Web Api 5.2.3 which I don't want to have a dependency on especially with the current flux of .net and .net core and future support.

I can't find in any of the repos (my github/google-fu is failing me) to find the `HttpClientFactory` source to see what it actually does but I do like the idea of the message handlers and think it should be explored further :-)

**Comment by mxa0079** [comment]
Good point. I would not like to take a dependency on Web API on a client library either. However, it looks like it is our lucky day: `HttpClient` also provides a constructor where we can pass an `HttpMessageHandler`. I will experiment with this and update.

**Comment by WestDiscGolf** [comment]
I've been thinking about the Http Message Handlers and I think using these as extension points is good. Not only can we add logging etc. but another usage is we can also use them to have a handler to extract out the rate limit information so consumers can check usage etc - https://dev.fitbit.com/docs/basics/#response-headers

If the constructor of the `FitbitClient` takes in an optional params of message handlers then they can run in order, almost like the OWIN request pipeline.

This then allows us to add some ones which can be used in the box - eg logging, rate info extraction - but also consumers can add in additional ones for their own needs.

**Comment by WestDiscGolf** [comment]
See discussion #82

**Comment by mxa0079** [comment]
Initial implementation merged. Closing issue.
