### ISSUE TITLE
BUG - Intra day data parsing

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#66]
The time value of the intra day data parsing gets the value from the Time property in the json however as the parent node isn't referenced and the actual day you are parsing isn't passed in the value defined is actually the current date - this fails the unit test. I believe this to be a valid failure as I would expect the time of the intra day value to be linked to the request day date

**Comment by aarondcoleman** [comment]
Where in code is this?

**Comment by WestDiscGolf** [comment]
The test which is failing is `GetIntraDayTimeSeriesAsync_Success` and the method which will need updating is `GetIntradayTimeSeriesData` in the JsonDotNetSerializerExtensions.cs

**Comment by WestDiscGolf** [comment]
Had a look at this during lunch time, think I know what the issue is and working on fix. Should hopefully get a PR in soon for it.

**Comment by WestDiscGolf** [comment]
Fixed in #71

**Comment by WestDiscGolf** [comment]
Ping :-)

**Comment by mxa0079** [comment]
Added a couple of comments to PR. Waiting for that before merging and closing this issue.

**Comment by WestDiscGolf** [comment]
@mxa0079 updated :-)

**Comment by WestDiscGolf** [comment]
Re-done the PR :-)

**Comment by WestDiscGolf** [comment]
PR merged
