### ISSUE TITLE
Json.Net upgrade for RC of v2?

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#67]
We're currently running on version 6.0.3 of Json.Net which came out in March 2014 and the current version is 8.0.2 (https://www.nuget.org/packages/Newtonsoft.Json/), which is 2 major versions behind. Thoughts?

**Comment by mxa0079** [comment]
My vote goes towards adding this to the bottom of our backlog for V2 milestone.

**Comment by WestDiscGolf** [comment]
Any reason why not to upgrade for the v2 RC?

**Comment by aarondcoleman** [comment]
I don't see any breaking changes listed... and we have unit tests around all the serialization right? Might be worth branching, testing, and if it's not an issue, merging in:
https://github.com/JamesNK/Newtonsoft.Json/releases

**Comment by mxa0079** [comment]
I agree on @aarondcoleman's suggested approach. However, assuming the library owners are using [semantic versioning] (http://semver.org/), then we should expect some breaking changes since the library is now 2 major versions ahead.

**Comment by WestDiscGolf** [comment]
Agree - yes there are / should be serialization tests for all models. If not then we should add issues for each model which is missing them and add them in.

As for version bumps for Json.NET I believe there was some minor api changes from 6 to 7 however the bump from 7 to 8 seems purely performance and bug fixes related from what I can see. I can only assume the workings under the hood have changed so much and what it's trying to support is altering that a major version bump was required to indicate such a large change (guessing dotnet core is involved somewhere).

Branch, update and give it a whirl I say :-)

**Comment by mxa0079** [comment]
Aaaand we are on Json.Net 8.0.2 =D

**Comment by WestDiscGolf** [comment]
Boom! :-)
