### ISSUE TITLE
Parse rate limit from api responses in HandleRequest

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#74]
According to the Fitbit api documentation each response returns additional information about its rate limits. This information might be useful to be parsed out.

I'm not sure where it should go or if it would be useful or what the use case would be but thought I would add this issue to allow for discussion.

Further info - https://dev.fitbit.com/docs/basics/#response-headers

**Comment by WestDiscGolf** [comment]
On further thought I think this should be done via the http message handler extension pipeline which is being discussed for the logging etc. See #63

**Comment by WestDiscGolf** [comment]
I think this could be done with an interceptor - I don't think this needs to be in core library but as part of the documentation would be cool as example of what can be done.

**Comment by mxa0079** [comment]
This could be implemented as an `IFitbitResponse` using the changes in PR #112

**Comment by WestDiscGolf** [comment]
:+1: One for the documentation / examples I think

Closing ...
