### ISSUE TITLE
Is Fitbit.Common still needed?

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#78]
If we are retiring V1, do we still need FitBit.Common or can that be merged into FitBit.Portable to have a single project?

**Comment by WestDiscGolf** [comment]
Was purely there to keep the old and new versions referencing the same models but not each other. Happy to move them back into Portable project

**Comment by WestDiscGolf** [comment]
To do this the old version needs to be deleted from the solution and the old example projects removed. Once master has been branched to create the v1 then we should do this before merging async-portable into master.

**Comment by WestDiscGolf** [comment]
@aarondcoleman @mxa0079 are we removing the v1 completely for v2 release?
