### ISSUE TITLE
Re-enable tests that have been tagged with "Ignore" attribute

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#79]
A set of tests have been tagged with: [Ignore("Re-enable when exceptions have been introduced")]

Well... the exceptions have been re-introduced so it is time t bring them back on board. This should be done before RC to ensure no major functionality has been broken as part of new functionality.

**Comment by WestDiscGolf** [comment]
Agree these should be updated for RC

**Comment by WestDiscGolf** [comment]
Looking at these now ...

**Comment by WestDiscGolf** [comment]
PR #84

**Comment by mxa0079** [comment]
PR #84 merged
