### ISSUE TITLE
Ambigous behavior in FitbitClient constructor - redundant arguments

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#82]
The [constructor for FitBitClient] (https://github.com/aarondcoleman/Fitbit.NET/blob/async-portable/Fitbit.Portable/FitbitClient.cs#L23) has redundant arguments. The `Httpclient` argument is to be used if we have a client whose authentication headers have already been set, hence there is no need to provie an implementation of `IAuthorization` (client is already authorized). And vice-versa, if we are providing an implementation of `IAuthorization` then we want to take care of creating an authorized `HttpClient` through there and there is no need to pass our own client.

Possible solutions:

- Create two different constructors: one for `IAuthorization` and another one were we simply pass `HttpClient`

- Remove `HttpClient` as an argument

Thoughts?

**Comment by WestDiscGolf** [comment]
I'm not sure how much passing in a HttpClient helps? I think we should keep the construction of the HttpClient internal and handle things like Authorization etc. through extension points. Simple constructor which can take nothing in and just work but also have optional parameters to pass in additional arguments which add to extending the functionality eg. the message handlers we add to the request pipeline

**Comment by WestDiscGolf** [comment]
I don't think we want to allow a HttpClient in the constructor of the FitbitClient however we will have to come up with another way of injecting in the httpclient for the tests ... eg

```        
public static FitbitClient CreateFitbitClient(Func<HttpResponseMessage> response, Action<HttpRequestMessage, CancellationToken> verificationCallback)
        {
            var handler = new Mock<HttpMessageHandler>();
            handler.Protected()
                .Setup<Task<HttpResponseMessage>>("SendAsync", ItExpr.IsAny<HttpRequestMessage>(), ItExpr.IsAny<CancellationToken>())
                .Returns(Task<HttpResponseMessage>.Factory.StartNew(response))
                .Callback(verificationCallback);
            var httpClient = new HttpClient(handler.Object);
            return new FitbitClient(httpClient);
        }
```

**Comment by WestDiscGolf** [comment]
A plan is being mulled over, trying to work out how to do it ...

**Comment by mxa0079** [comment]
Hey @WestDiscGolf, I have been working on this since yesterday. I am planning on using the same `IFitbitClientInterceptor` to be able to shortcircuit HttpClient and provide fake responses. 

Something like this:

```csharp
    public interface IFitbitClientInterceptor
    {
        Task<HttpResponseMessage> InterceptRequest(HttpRequestMessage request, CancellationToken cancellationToken);
        void InterceptResponse(HttpResponseMessage response, CancellationToken cancellationToken);
    }
```

You can see the WIP on my oauth2-httphandler branch.

**Comment by WestDiscGolf** [comment]
@mxa0079 it sounds like we're thinking along the same lines. I've gone a step further though and would like you to take a look - https://github.com/WestDiscGolf/Fitbit.NET/tree/pipeline-processing

What I've done ...

1. Reduced the constructors down to 1 in FitbitClient

2. Left the `IFitbitClientInterceptor` as is

3. Updated `FitbitMessageHandler` (previously known as `FitbitHttpClientMessageHandler`) to be a wrapper around the interceptor

4. In `FitbitClientHelperExtensions` there is now a helper method called `CreatePipeline` which creates the message handlers to construct the HttpClient instance.

5. Using the Russian doll type of scenario it builds up a processing pipeline which each request goes through - for logging etc.

6. I have updated 'IAuthorization` and hence `OAuth2Authorization` to be a special interceptor so it adds in the authorisation http header on each request by itself.

I've unloaded some of the projects as they won't all build as I've essentially given up on OAuth1 for this example.

Let me know what you think.

**Comment by WestDiscGolf** [comment]
@mxa0079 did you have a chance to look at my branch?

**Comment by mxa0079** [comment]
@WestDiscGolf It is next on my to-do list. I am looking forward to it!

**Comment by mxa0079** [comment]
Closing this issue as the constructors have been simplified. @WestDiscGolf I see advantages to allowing multiple IFitbitInterceptors (will result in a cleaner `FitbitHttpClientMessageHandler`), and I also like the rename of that class. However, I share @aarondcoleman concern's on the overkill of param [] in the main constructor. Maybe we can reach a happy compromise =D.

**Comment by WestDiscGolf** [comment]
@mxa0079 @aarondcoleman I'd like to understand why params are overkill? The whole point of params is you don't have to use them or you can pass in as many as you like. It leaves the simple scenario open and allows extensibility. We can make some constructor overrides to make it even clearer if you think that's the problem. Happy to discuss as I think we're both looking at the same issue from different view points and I think we could get to a good solution.
