### ISSUE TITLE
Migrate to new Nuget package restore mechanism.

### ISSUE THREAD

**Issue by mxa0079** [aarondcoleman/Fitbit.NET#88]
A bit of house cleaning-- starting in V2.7 nuget released a new/more robust package restore approach.

Details here: http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore

**Comment by mxa0079** [comment]
This is fixed in PR #90

**Comment by WestDiscGolf** [comment]
Nice! :-)
